version: '3.7'

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.htpasswd:/.htpasswd"
    networks:
      - proxy

networks:
  proxy:
    external: true
