version: '3'

services:

  openmu-startup:
    build:
      context: ../../src
      dockerfile: Startup/Dockerfile
    restart: "no"
    ports:
      - "8081:8080"

  database:
    ports:
      - "5433:5432"
